package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * AcademicPerformance generated by hbm2java
 */
@Entity
@Table(name="academic_performance"
)
public class AcademicPerformance  implements java.io.Serializable {


     private String email;
     private Pi pi;
     private Double avgSchoolPer;
     private Short schoolRepeats;
     private Double avgCollegePer;
     private Short collegeYearRepeats;
     private Short collegeSubRepeats;
     private Double avgPgPer;
     private Short pgYearRepeats;
     private Short pgSubRepeats;

    public AcademicPerformance() {
    }

	
    public AcademicPerformance(Pi pi) {
        this.pi = pi;
    }
    public AcademicPerformance(Pi pi, Double avgSchoolPer, Short schoolRepeats, Double avgCollegePer, Short collegeYearRepeats, Short collegeSubRepeats, Double avgPgPer, Short pgYearRepeats, Short pgSubRepeats) {
       this.pi = pi;
       this.avgSchoolPer = avgSchoolPer;
       this.schoolRepeats = schoolRepeats;
       this.avgCollegePer = avgCollegePer;
       this.collegeYearRepeats = collegeYearRepeats;
       this.collegeSubRepeats = collegeSubRepeats;
       this.avgPgPer = avgPgPer;
       this.pgYearRepeats = pgYearRepeats;
       this.pgSubRepeats = pgSubRepeats;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="pi"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="email", unique=true, nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Pi getPi() {
        return this.pi;
    }
    
    public void setPi(Pi pi) {
        this.pi = pi;
    }

    
    @Column(name="avg_school_per", precision=17, scale=17)
    public Double getAvgSchoolPer() {
        return this.avgSchoolPer;
    }
    
    public void setAvgSchoolPer(Double avgSchoolPer) {
        this.avgSchoolPer = avgSchoolPer;
    }

    
    @Column(name="school_repeats")
    public Short getSchoolRepeats() {
        return this.schoolRepeats;
    }
    
    public void setSchoolRepeats(Short schoolRepeats) {
        this.schoolRepeats = schoolRepeats;
    }

    
    @Column(name="avg_college_per", precision=17, scale=17)
    public Double getAvgCollegePer() {
        return this.avgCollegePer;
    }
    
    public void setAvgCollegePer(Double avgCollegePer) {
        this.avgCollegePer = avgCollegePer;
    }

    
    @Column(name="college_year_repeats")
    public Short getCollegeYearRepeats() {
        return this.collegeYearRepeats;
    }
    
    public void setCollegeYearRepeats(Short collegeYearRepeats) {
        this.collegeYearRepeats = collegeYearRepeats;
    }

    
    @Column(name="college_sub_repeats")
    public Short getCollegeSubRepeats() {
        return this.collegeSubRepeats;
    }
    
    public void setCollegeSubRepeats(Short collegeSubRepeats) {
        this.collegeSubRepeats = collegeSubRepeats;
    }

    
    @Column(name="avg_pg_per", precision=17, scale=17)
    public Double getAvgPgPer() {
        return this.avgPgPer;
    }
    
    public void setAvgPgPer(Double avgPgPer) {
        this.avgPgPer = avgPgPer;
    }

    
    @Column(name="pg_year_repeats")
    public Short getPgYearRepeats() {
        return this.pgYearRepeats;
    }
    
    public void setPgYearRepeats(Short pgYearRepeats) {
        this.pgYearRepeats = pgYearRepeats;
    }

    
    @Column(name="pg_sub_repeats")
    public Short getPgSubRepeats() {
        return this.pgSubRepeats;
    }
    
    public void setPgSubRepeats(Short pgSubRepeats) {
        this.pgSubRepeats = pgSubRepeats;
    }




}


