package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AddictionsId generated by hbm2java
 */
@Embeddable
public class AddictionsId  implements java.io.Serializable {


     private String email;
     private String addiction;

    public AddictionsId() {
    }

    public AddictionsId(String email, String addiction) {
       this.email = email;
       this.addiction = addiction;
    }
   


    @Column(name="email", nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }


    @Column(name="addiction", nullable=false)
    public String getAddiction() {
        return this.addiction;
    }
    
    public void setAddiction(String addiction) {
        this.addiction = addiction;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AddictionsId) ) return false;
		 AddictionsId castOther = ( AddictionsId ) other; 
         
		 return ( (this.getEmail()==castOther.getEmail()) || ( this.getEmail()!=null && castOther.getEmail()!=null && this.getEmail().equals(castOther.getEmail()) ) )
 && ( (this.getAddiction()==castOther.getAddiction()) || ( this.getAddiction()!=null && castOther.getAddiction()!=null && this.getAddiction().equals(castOther.getAddiction()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEmail() == null ? 0 : this.getEmail().hashCode() );
         result = 37 * result + ( getAddiction() == null ? 0 : this.getAddiction().hashCode() );
         return result;
   }   


}


