package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FamilyRelations generated by hbm2java
 */
@Entity
@Table(name="family_relations"
)
public class FamilyRelations  implements java.io.Serializable {


     private FamilyRelationsId id;
     private Pi pi;
     private String qual;
     private String profession;
     private String income;
     private Boolean isdeceased;
     private String gender;

    public FamilyRelations() {
    }

	
    public FamilyRelations(FamilyRelationsId id, Pi pi) {
        this.id = id;
        this.pi = pi;
    }
    public FamilyRelations(FamilyRelationsId id, Pi pi, String qual, String profession, String income, Boolean isdeceased, String gender) {
       this.id = id;
       this.pi = pi;
       this.qual = qual;
       this.profession = profession;
       this.income = income;
       this.isdeceased = isdeceased;
       this.gender = gender;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="email", column=@Column(name="email", nullable=false) ), 
        @AttributeOverride(name="relType", column=@Column(name="rel_type", nullable=false) ), 
        @AttributeOverride(name="personName", column=@Column(name="person_name", nullable=false) ) } )
    public FamilyRelationsId getId() {
        return this.id;
    }
    
    public void setId(FamilyRelationsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="email", nullable=false, insertable=false, updatable=false)
    public Pi getPi() {
        return this.pi;
    }
    
    public void setPi(Pi pi) {
        this.pi = pi;
    }

    
    @Column(name="qual")
    public String getQual() {
        return this.qual;
    }
    
    public void setQual(String qual) {
        this.qual = qual;
    }

    
    @Column(name="profession")
    public String getProfession() {
        return this.profession;
    }
    
    public void setProfession(String profession) {
        this.profession = profession;
    }

    
    @Column(name="income")
    public String getIncome() {
        return this.income;
    }
    
    public void setIncome(String income) {
        this.income = income;
    }

    
    @Column(name="isdeceased")
    public Boolean getIsdeceased() {
        return this.isdeceased;
    }
    
    public void setIsdeceased(Boolean isdeceased) {
        this.isdeceased = isdeceased;
    }

    
    @Column(name="gender")
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }




}


