package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FriendsId generated by hbm2java
 */
@Embeddable
public class FriendsId  implements java.io.Serializable {


     private String email;
     private String FName;

    public FriendsId() {
    }

    public FriendsId(String email, String FName) {
       this.email = email;
       this.FName = FName;
    }
   


    @Column(name="email", nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }


    @Column(name="f_name", nullable=false)
    public String getFName() {
        return this.FName;
    }
    
    public void setFName(String FName) {
        this.FName = FName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FriendsId) ) return false;
		 FriendsId castOther = ( FriendsId ) other; 
         
		 return ( (this.getEmail()==castOther.getEmail()) || ( this.getEmail()!=null && castOther.getEmail()!=null && this.getEmail().equals(castOther.getEmail()) ) )
 && ( (this.getFName()==castOther.getFName()) || ( this.getFName()!=null && castOther.getFName()!=null && this.getFName().equals(castOther.getFName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEmail() == null ? 0 : this.getEmail().hashCode() );
         result = 37 * result + ( getFName() == null ? 0 : this.getFName().hashCode() );
         return result;
   }   


}


