package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IdolsId generated by hbm2java
 */
@Embeddable
public class IdolsId  implements java.io.Serializable {


     private String email;
     private String idolName;

    public IdolsId() {
    }

    public IdolsId(String email, String idolName) {
       this.email = email;
       this.idolName = idolName;
    }
   


    @Column(name="email", nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }


    @Column(name="idol_name", nullable=false)
    public String getIdolName() {
        return this.idolName;
    }
    
    public void setIdolName(String idolName) {
        this.idolName = idolName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IdolsId) ) return false;
		 IdolsId castOther = ( IdolsId ) other; 
         
		 return ( (this.getEmail()==castOther.getEmail()) || ( this.getEmail()!=null && castOther.getEmail()!=null && this.getEmail().equals(castOther.getEmail()) ) )
 && ( (this.getIdolName()==castOther.getIdolName()) || ( this.getIdolName()!=null && castOther.getIdolName()!=null && this.getIdolName().equals(castOther.getIdolName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEmail() == null ? 0 : this.getEmail().hashCode() );
         result = 37 * result + ( getIdolName() == null ? 0 : this.getIdolName().hashCode() );
         return result;
   }   


}


