package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IncidencesId generated by hbm2java
 */
@Embeddable
public class IncidencesId  implements java.io.Serializable {


     private String email;
     private String incidenceName;

    public IncidencesId() {
    }

    public IncidencesId(String email, String incidenceName) {
       this.email = email;
       this.incidenceName = incidenceName;
    }
   


    @Column(name="email", nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }


    @Column(name="incidence_name", nullable=false)
    public String getIncidenceName() {
        return this.incidenceName;
    }
    
    public void setIncidenceName(String incidenceName) {
        this.incidenceName = incidenceName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IncidencesId) ) return false;
		 IncidencesId castOther = ( IncidencesId ) other; 
         
		 return ( (this.getEmail()==castOther.getEmail()) || ( this.getEmail()!=null && castOther.getEmail()!=null && this.getEmail().equals(castOther.getEmail()) ) )
 && ( (this.getIncidenceName()==castOther.getIncidenceName()) || ( this.getIncidenceName()!=null && castOther.getIncidenceName()!=null && this.getIncidenceName().equals(castOther.getIncidenceName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEmail() == null ? 0 : this.getEmail().hashCode() );
         result = 37 * result + ( getIncidenceName() == null ? 0 : this.getIncidenceName().hashCode() );
         return result;
   }   


}


