package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InfluentialPersonalitiesId generated by hbm2java
 */
@Embeddable
public class InfluentialPersonalitiesId  implements java.io.Serializable {


     private String email;
     private String personalityName;

    public InfluentialPersonalitiesId() {
    }

    public InfluentialPersonalitiesId(String email, String personalityName) {
       this.email = email;
       this.personalityName = personalityName;
    }
   


    @Column(name="email", nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }


    @Column(name="personality_name", nullable=false)
    public String getPersonalityName() {
        return this.personalityName;
    }
    
    public void setPersonalityName(String personalityName) {
        this.personalityName = personalityName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InfluentialPersonalitiesId) ) return false;
		 InfluentialPersonalitiesId castOther = ( InfluentialPersonalitiesId ) other; 
         
		 return ( (this.getEmail()==castOther.getEmail()) || ( this.getEmail()!=null && castOther.getEmail()!=null && this.getEmail().equals(castOther.getEmail()) ) )
 && ( (this.getPersonalityName()==castOther.getPersonalityName()) || ( this.getPersonalityName()!=null && castOther.getPersonalityName()!=null && this.getPersonalityName().equals(castOther.getPersonalityName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEmail() == null ? 0 : this.getEmail().hashCode() );
         result = 37 * result + ( getPersonalityName() == null ? 0 : this.getPersonalityName().hashCode() );
         return result;
   }   


}


