package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * MealType generated by hbm2java
 */
@Entity
@Table(name="meal_type", schema="test"
)
public class MealType  implements java.io.Serializable {


     private String email;
     private Pi pi;
     private String diet;
     private Short nonvegDaysPerWeek;
     private String foodType;
     private Short fruitsDaysPerWeek;
     private Short eatingOutDaysPerWeek;

    public MealType() {
    }

	
    public MealType(Pi pi) {
        this.pi = pi;
    }
    public MealType(Pi pi, String diet, Short nonvegDaysPerWeek, String foodType, Short fruitsDaysPerWeek, Short eatingOutDaysPerWeek) {
       this.pi = pi;
       this.diet = diet;
       this.nonvegDaysPerWeek = nonvegDaysPerWeek;
       this.foodType = foodType;
       this.fruitsDaysPerWeek = fruitsDaysPerWeek;
       this.eatingOutDaysPerWeek = eatingOutDaysPerWeek;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="pi"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="email", unique=true, nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Pi getPi() {
        return this.pi;
    }
    
    public void setPi(Pi pi) {
        this.pi = pi;
    }

    
    @Column(name="diet")
    public String getDiet() {
        return this.diet;
    }
    
    public void setDiet(String diet) {
        this.diet = diet;
    }

    
    @Column(name="nonveg_days_per_week")
    public Short getNonvegDaysPerWeek() {
        return this.nonvegDaysPerWeek;
    }
    
    public void setNonvegDaysPerWeek(Short nonvegDaysPerWeek) {
        this.nonvegDaysPerWeek = nonvegDaysPerWeek;
    }

    
    @Column(name="food_type")
    public String getFoodType() {
        return this.foodType;
    }
    
    public void setFoodType(String foodType) {
        this.foodType = foodType;
    }

    
    @Column(name="fruits_days_per_week")
    public Short getFruitsDaysPerWeek() {
        return this.fruitsDaysPerWeek;
    }
    
    public void setFruitsDaysPerWeek(Short fruitsDaysPerWeek) {
        this.fruitsDaysPerWeek = fruitsDaysPerWeek;
    }

    
    @Column(name="eating_out_days_per_week")
    public Short getEatingOutDaysPerWeek() {
        return this.eatingOutDaysPerWeek;
    }
    
    public void setEatingOutDaysPerWeek(Short eatingOutDaysPerWeek) {
        this.eatingOutDaysPerWeek = eatingOutDaysPerWeek;
    }




}


