package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Menses generated by hbm2java
 */
@Entity
@Table(name="menses"
)
public class Menses  implements java.io.Serializable {


     private String email;
     private Pi pi;
     private Boolean irregular;
     private Boolean painful;
     private Boolean heavy;
     private Short hysterectomyAge;

    public Menses() {
    }

	
    public Menses(Pi pi) {
        this.pi = pi;
    }
    public Menses(Pi pi, Boolean irregular, Boolean painful, Boolean heavy, Short hysterectomyAge) {
       this.pi = pi;
       this.irregular = irregular;
       this.painful = painful;
       this.heavy = heavy;
       this.hysterectomyAge = hysterectomyAge;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="pi"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="email", unique=true, nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Pi getPi() {
        return this.pi;
    }
    
    public void setPi(Pi pi) {
        this.pi = pi;
    }

    
    @Column(name="irregular")
    public Boolean getIrregular() {
        return this.irregular;
    }
    
    public void setIrregular(Boolean irregular) {
        this.irregular = irregular;
    }

    
    @Column(name="painful")
    public Boolean getPainful() {
        return this.painful;
    }
    
    public void setPainful(Boolean painful) {
        this.painful = painful;
    }

    
    @Column(name="heavy")
    public Boolean getHeavy() {
        return this.heavy;
    }
    
    public void setHeavy(Boolean heavy) {
        this.heavy = heavy;
    }

    
    @Column(name="hysterectomy_age")
    public Short getHysterectomyAge() {
        return this.hysterectomyAge;
    }
    
    public void setHysterectomyAge(Short hysterectomyAge) {
        this.hysterectomyAge = hysterectomyAge;
    }




}


