package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * PhysicalParams generated by hbm2java
 */
@Entity
@Table(name="physical_params"
)
public class PhysicalParams  implements java.io.Serializable {


     private String email;
     private Pi pi;
     private Double heightFeets;
     private Double heightInches;
     private Double heightCm;
     private Double weight;
     private Double hip;
     private Double waist;
     private Double bp;
     private Double haemoglobin;
     private String toeTouching;
     private Double toeTouchingCm;
     private Short looseMoPerWeek;
     private Short constipationPerWeek;

    public PhysicalParams() {
    }

	
    public PhysicalParams(Pi pi) {
        this.pi = pi;
    }
    public PhysicalParams(Pi pi, Double heightFeets, Double heightInches, Double heightCm, Double weight, Double hip, Double waist, Double bp, Double haemoglobin, String toeTouching, Double toeTouchingCm, Short looseMoPerWeek, Short constipationPerWeek) {
       this.pi = pi;
       this.heightFeets = heightFeets;
       this.heightInches = heightInches;
       this.heightCm = heightCm;
       this.weight = weight;
       this.hip = hip;
       this.waist = waist;
       this.bp = bp;
       this.haemoglobin = haemoglobin;
       this.toeTouching = toeTouching;
       this.toeTouchingCm = toeTouchingCm;
       this.looseMoPerWeek = looseMoPerWeek;
       this.constipationPerWeek = constipationPerWeek;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="pi"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="email", unique=true, nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Pi getPi() {
        return this.pi;
    }
    
    public void setPi(Pi pi) {
        this.pi = pi;
    }

    
    @Column(name="height_feets", precision=17, scale=17)
    public Double getHeightFeets() {
        return this.heightFeets;
    }
    
    public void setHeightFeets(Double heightFeets) {
        this.heightFeets = heightFeets;
    }

    
    @Column(name="height_inches", precision=17, scale=17)
    public Double getHeightInches() {
        return this.heightInches;
    }
    
    public void setHeightInches(Double heightInches) {
        this.heightInches = heightInches;
    }

    
    @Column(name="height_cm", precision=17, scale=17)
    public Double getHeightCm() {
        return this.heightCm;
    }
    
    public void setHeightCm(Double heightCm) {
        this.heightCm = heightCm;
    }

    
    @Column(name="weight", precision=17, scale=17)
    public Double getWeight() {
        return this.weight;
    }
    
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    
    @Column(name="hip", precision=17, scale=17)
    public Double getHip() {
        return this.hip;
    }
    
    public void setHip(Double hip) {
        this.hip = hip;
    }

    
    @Column(name="waist", precision=17, scale=17)
    public Double getWaist() {
        return this.waist;
    }
    
    public void setWaist(Double waist) {
        this.waist = waist;
    }

    
    @Column(name="bp", precision=17, scale=17)
    public Double getBp() {
        return this.bp;
    }
    
    public void setBp(Double bp) {
        this.bp = bp;
    }

    
    @Column(name="haemoglobin", precision=17, scale=17)
    public Double getHaemoglobin() {
        return this.haemoglobin;
    }
    
    public void setHaemoglobin(Double haemoglobin) {
        this.haemoglobin = haemoglobin;
    }

    
    @Column(name="toe_touching")
    public String getToeTouching() {
        return this.toeTouching;
    }
    
    public void setToeTouching(String toeTouching) {
        this.toeTouching = toeTouching;
    }

    
    @Column(name="toe_touching_cm", precision=17, scale=17)
    public Double getToeTouchingCm() {
        return this.toeTouchingCm;
    }
    
    public void setToeTouchingCm(Double toeTouchingCm) {
        this.toeTouchingCm = toeTouchingCm;
    }

    
    @Column(name="loose_mo_per_week")
    public Short getLooseMoPerWeek() {
        return this.looseMoPerWeek;
    }
    
    public void setLooseMoPerWeek(Short looseMoPerWeek) {
        this.looseMoPerWeek = looseMoPerWeek;
    }

    
    @Column(name="constipation_per_week")
    public Short getConstipationPerWeek() {
        return this.constipationPerWeek;
    }
    
    public void setConstipationPerWeek(Short constipationPerWeek) {
        this.constipationPerWeek = constipationPerWeek;
    }




}


