package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TastesId generated by hbm2java
 */
@Embeddable
public class TastesId  implements java.io.Serializable {


     private String email;
     private String tasteName;

    public TastesId() {
    }

    public TastesId(String email, String tasteName) {
       this.email = email;
       this.tasteName = tasteName;
    }
   


    @Column(name="email", nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }


    @Column(name="taste_name", nullable=false)
    public String getTasteName() {
        return this.tasteName;
    }
    
    public void setTasteName(String tasteName) {
        this.tasteName = tasteName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TastesId) ) return false;
		 TastesId castOther = ( TastesId ) other; 
         
		 return ( (this.getEmail()==castOther.getEmail()) || ( this.getEmail()!=null && castOther.getEmail()!=null && this.getEmail().equals(castOther.getEmail()) ) )
 && ( (this.getTasteName()==castOther.getTasteName()) || ( this.getTasteName()!=null && castOther.getTasteName()!=null && this.getTasteName().equals(castOther.getTasteName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEmail() == null ? 0 : this.getEmail().hashCode() );
         result = 37 * result + ( getTasteName() == null ? 0 : this.getTasteName().hashCode() );
         return result;
   }   


}


