package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Vehicles generated by hbm2java
 */
@Entity
@Table(name="vehicles"
)
public class Vehicles  implements java.io.Serializable {


     private VehiclesId id;
     private Pi pi;
     private Short vehicleNumbers;

    public Vehicles() {
    }

	
    public Vehicles(VehiclesId id, Pi pi) {
        this.id = id;
        this.pi = pi;
    }
    public Vehicles(VehiclesId id, Pi pi, Short vehicleNumbers) {
       this.id = id;
       this.pi = pi;
       this.vehicleNumbers = vehicleNumbers;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="email", column=@Column(name="email", nullable=false) ), 
        @AttributeOverride(name="vehicleType", column=@Column(name="vehicle_type", nullable=false) ) } )
    public VehiclesId getId() {
        return this.id;
    }
    
    public void setId(VehiclesId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="email", nullable=false, insertable=false, updatable=false)
    public Pi getPi() {
        return this.pi;
    }
    
    public void setPi(Pi pi) {
        this.pi = pi;
    }

    
    @Column(name="vehicle_numbers")
    public Short getVehicleNumbers() {
        return this.vehicleNumbers;
    }
    
    public void setVehicleNumbers(Short vehicleNumbers) {
        this.vehicleNumbers = vehicleNumbers;
    }




}


