package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Addictions generated by hbm2java
 */
@Entity
@Table(name="addictions", schema="test"
)
public class Addictions  implements java.io.Serializable {


     private AddictionsId id;
     private Pi pi;
     private Short frequency;

    public Addictions() {
    }

	
    public Addictions(AddictionsId id, Pi pi) {
        this.id = id;
        this.pi = pi;
    }
    public Addictions(AddictionsId id, Pi pi, Short frequency) {
       this.id = id;
       this.pi = pi;
       this.frequency = frequency;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="email", column=@Column(name="email", nullable=false) ), 
        @AttributeOverride(name="addiction", column=@Column(name="addiction", nullable=false) ) } )
    public AddictionsId getId() {
        return this.id;
    }
    
    public void setId(AddictionsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="email", nullable=false, insertable=false, updatable=false)
    public Pi getPi() {
        return this.pi;
    }
    
    public void setPi(Pi pi) {
        this.pi = pi;
    }

    
    @Column(name="frequency")
    public Short getFrequency() {
        return this.frequency;
    }
    
    public void setFrequency(Short frequency) {
        this.frequency = frequency;
    }




}


