package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AllergiesId generated by hbm2java
 */
@Embeddable
public class AllergiesId  implements java.io.Serializable {


     private String email;
     private String allergyName;

    public AllergiesId() {
    }

    public AllergiesId(String email, String allergyName) {
       this.email = email;
       this.allergyName = allergyName;
    }
   


    @Column(name="email", nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }


    @Column(name="allergy_name", nullable=false)
    public String getAllergyName() {
        return this.allergyName;
    }
    
    public void setAllergyName(String allergyName) {
        this.allergyName = allergyName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AllergiesId) ) return false;
		 AllergiesId castOther = ( AllergiesId ) other; 
         
		 return ( (this.getEmail()==castOther.getEmail()) || ( this.getEmail()!=null && castOther.getEmail()!=null && this.getEmail().equals(castOther.getEmail()) ) )
 && ( (this.getAllergyName()==castOther.getAllergyName()) || ( this.getAllergyName()!=null && castOther.getAllergyName()!=null && this.getAllergyName().equals(castOther.getAllergyName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEmail() == null ? 0 : this.getEmail().hashCode() );
         result = 37 * result + ( getAllergyName() == null ? 0 : this.getAllergyName().hashCode() );
         return result;
   }   


}


