package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EntertainmentId generated by hbm2java
 */
@Embeddable
public class EntertainmentId  implements java.io.Serializable {


     private String email;
     private String entType;

    public EntertainmentId() {
    }

    public EntertainmentId(String email, String entType) {
       this.email = email;
       this.entType = entType;
    }
   


    @Column(name="email", nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }


    @Column(name="ent_type", nullable=false)
    public String getEntType() {
        return this.entType;
    }
    
    public void setEntType(String entType) {
        this.entType = entType;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EntertainmentId) ) return false;
		 EntertainmentId castOther = ( EntertainmentId ) other; 
         
		 return ( (this.getEmail()==castOther.getEmail()) || ( this.getEmail()!=null && castOther.getEmail()!=null && this.getEmail().equals(castOther.getEmail()) ) )
 && ( (this.getEntType()==castOther.getEntType()) || ( this.getEntType()!=null && castOther.getEntType()!=null && this.getEntType().equals(castOther.getEntType()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEmail() == null ? 0 : this.getEmail().hashCode() );
         result = 37 * result + ( getEntType() == null ? 0 : this.getEntType().hashCode() );
         return result;
   }   


}


