package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FamilyRelationsId generated by hbm2java
 */
@Embeddable
public class FamilyRelationsId  implements java.io.Serializable {


     private String email;
     private String relType;
     private String personName;

    public FamilyRelationsId() {
    }

    public FamilyRelationsId(String email, String relType, String personName) {
       this.email = email;
       this.relType = relType;
       this.personName = personName;
    }
   


    @Column(name="email", nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }


    @Column(name="rel_type", nullable=false)
    public String getRelType() {
        return this.relType;
    }
    
    public void setRelType(String relType) {
        this.relType = relType;
    }


    @Column(name="person_name", nullable=false)
    public String getPersonName() {
        return this.personName;
    }
    
    public void setPersonName(String personName) {
        this.personName = personName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FamilyRelationsId) ) return false;
		 FamilyRelationsId castOther = ( FamilyRelationsId ) other; 
         
		 return ( (this.getEmail()==castOther.getEmail()) || ( this.getEmail()!=null && castOther.getEmail()!=null && this.getEmail().equals(castOther.getEmail()) ) )
 && ( (this.getRelType()==castOther.getRelType()) || ( this.getRelType()!=null && castOther.getRelType()!=null && this.getRelType().equals(castOther.getRelType()) ) )
 && ( (this.getPersonName()==castOther.getPersonName()) || ( this.getPersonName()!=null && castOther.getPersonName()!=null && this.getPersonName().equals(castOther.getPersonName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEmail() == null ? 0 : this.getEmail().hashCode() );
         result = 37 * result + ( getRelType() == null ? 0 : this.getRelType().hashCode() );
         result = 37 * result + ( getPersonName() == null ? 0 : this.getPersonName().hashCode() );
         return result;
   }   


}


