package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HobbiesId generated by hbm2java
 */
@Embeddable
public class HobbiesId  implements java.io.Serializable {


     private String email;
     private String hobby;

    public HobbiesId() {
    }

    public HobbiesId(String email, String hobby) {
       this.email = email;
       this.hobby = hobby;
    }
   


    @Column(name="email", nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }


    @Column(name="hobby", nullable=false)
    public String getHobby() {
        return this.hobby;
    }
    
    public void setHobby(String hobby) {
        this.hobby = hobby;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HobbiesId) ) return false;
		 HobbiesId castOther = ( HobbiesId ) other; 
         
		 return ( (this.getEmail()==castOther.getEmail()) || ( this.getEmail()!=null && castOther.getEmail()!=null && this.getEmail().equals(castOther.getEmail()) ) )
 && ( (this.getHobby()==castOther.getHobby()) || ( this.getHobby()!=null && castOther.getHobby()!=null && this.getHobby().equals(castOther.getHobby()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEmail() == null ? 0 : this.getEmail().hashCode() );
         result = 37 * result + ( getHobby() == null ? 0 : this.getHobby().hashCode() );
         return result;
   }   


}


