package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Hobbies generated by hbm2java
 */
@Entity
@Table(name="hobbies", schema="test"
)
public class Hobbies  implements java.io.Serializable {


     private HobbiesId id;
     private Pi pi;
     private Short hoursPerWeek;

    public Hobbies() {
    }

	
    public Hobbies(HobbiesId id, Pi pi) {
        this.id = id;
        this.pi = pi;
    }
    public Hobbies(HobbiesId id, Pi pi, Short hoursPerWeek) {
       this.id = id;
       this.pi = pi;
       this.hoursPerWeek = hoursPerWeek;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="email", column=@Column(name="email", nullable=false) ), 
        @AttributeOverride(name="hobby", column=@Column(name="hobby", nullable=false) ) } )
    public HobbiesId getId() {
        return this.id;
    }
    
    public void setId(HobbiesId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="email", nullable=false, insertable=false, updatable=false)
    public Pi getPi() {
        return this.pi;
    }
    
    public void setPi(Pi pi) {
        this.pi = pi;
    }

    
    @Column(name="hours_per_week")
    public Short getHoursPerWeek() {
        return this.hoursPerWeek;
    }
    
    public void setHoursPerWeek(Short hoursPerWeek) {
        this.hoursPerWeek = hoursPerWeek;
    }




}


