package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IllnessId generated by hbm2java
 */
@Embeddable
public class IllnessId  implements java.io.Serializable {


     private String email;
     private String illnessMember;
     private String illness;

    public IllnessId() {
    }

    public IllnessId(String email, String illnessMember, String illness) {
       this.email = email;
       this.illnessMember = illnessMember;
       this.illness = illness;
    }
   


    @Column(name="email", nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }


    @Column(name="illness_member", nullable=false)
    public String getIllnessMember() {
        return this.illnessMember;
    }
    
    public void setIllnessMember(String illnessMember) {
        this.illnessMember = illnessMember;
    }


    @Column(name="illness", nullable=false)
    public String getIllness() {
        return this.illness;
    }
    
    public void setIllness(String illness) {
        this.illness = illness;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IllnessId) ) return false;
		 IllnessId castOther = ( IllnessId ) other; 
         
		 return ( (this.getEmail()==castOther.getEmail()) || ( this.getEmail()!=null && castOther.getEmail()!=null && this.getEmail().equals(castOther.getEmail()) ) )
 && ( (this.getIllnessMember()==castOther.getIllnessMember()) || ( this.getIllnessMember()!=null && castOther.getIllnessMember()!=null && this.getIllnessMember().equals(castOther.getIllnessMember()) ) )
 && ( (this.getIllness()==castOther.getIllness()) || ( this.getIllness()!=null && castOther.getIllness()!=null && this.getIllness().equals(castOther.getIllness()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEmail() == null ? 0 : this.getEmail().hashCode() );
         result = 37 * result + ( getIllnessMember() == null ? 0 : this.getIllnessMember().hashCode() );
         result = 37 * result + ( getIllness() == null ? 0 : this.getIllness().hashCode() );
         return result;
   }   


}


