package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Illness generated by hbm2java
 */
@Entity
@Table(name="illness", schema="test"
)
public class Illness  implements java.io.Serializable {


     private IllnessId id;
     private Pi pi;
     private Boolean ishospitalized;
     
     private short intensity;
     private short frequency;
     private float duration;
     private short lastsForDays;
     private short sinceYears;
     private short lossOfManDays;

    public Illness() {
    }

	
    public Illness(IllnessId id, Pi pi) {
        this.id = id;
        this.pi = pi;
    }
    public Illness(IllnessId id, Pi pi, Boolean ishospitalized) {
       this.id = id;
       this.pi = pi;
       this.ishospitalized = ishospitalized;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="email", column=@Column(name="email", nullable=false) ), 
        @AttributeOverride(name="illnessMember", column=@Column(name="illness_member", nullable=false) ), 
        @AttributeOverride(name="illness", column=@Column(name="illness", nullable=false) ) } )
    public IllnessId getId() {
        return this.id;
    }
    
    public void setId(IllnessId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="email", nullable=false, insertable=false, updatable=false)
    public Pi getPi() {
        return this.pi;
    }
    
    public void setPi(Pi pi) {
        this.pi = pi;
    }

    
    @Column(name="ishospitalized")
    public Boolean getIshospitalized() {
        return this.ishospitalized;
    }
    
    public void setIshospitalized(Boolean ishospitalized) {
        this.ishospitalized = ishospitalized;
    }

    @Column(name="illness_intensity")
    public short getIntensity() {
        return intensity;
    }

    public void setIntensity(short intensity) {
        this.intensity = intensity;
    }

    @Column(name="illness_frequency")
    public short getFrequency() {
        return frequency;
    }

    public void setFrequency(short frequency) {
        this.frequency = frequency;
    }

    @Column(name="illness_duration")
    public float getDuration() {
        return duration;
    }

    public void setDuration(float duration) {
        this.duration = duration;
    }

    @Column(name="illness_lasts_for_days")
    public short getLastsForDays() {
        return lastsForDays;
    }

    public void setLastsForDays(short lastsForDays) {
        this.lastsForDays = lastsForDays;
    }

    @Column(name="illness_since_years")
    public short getSinceYears() {
        return sinceYears;
    }

    public void setSinceYears(short sinceYears) {
        this.sinceYears = sinceYears;
    }

    @Column(name="illness_loss_of_man_days")
    public short getLossOfManDays() {
        return lossOfManDays;
    }

    public void setLossOfManDays(short lossOfManDays) {
        this.lossOfManDays = lossOfManDays;
    }
}


