package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Pi generated by hbm2java
 */
@Entity
@Table(name="pi", schema="test"
)
public class Pi  implements java.io.Serializable {


     private String email;
     private Long recid;
     private String name;
     private Short age;
     private String gender;
     private String religion;
     private String maritalStatus;
     private Short noOfChildren;
     private Long mobile;
     private String qualification;
     private String profession;
     private String company;
     private String income;
     private Set<Incidences> incidenceses = new HashSet<Incidences>(0);
     private Address address;
     private Set<Illness> illnesses = new HashSet<Illness>(0);
     private Menses menses;
     private PhysicalParams physicalParams;
     private Set<Tastes> tasteses = new HashSet<Tastes>(0);
     private Travelling travelling;
     private MealType mealType;
     private SocialService socialService;
     private Set<Addictions> addictionses = new HashSet<Addictions>(0);
     private Exercise exercise;
     private AcademicPerformance academicPerformance;
     private Prayers prayers;
     private Set<Colours> colourses = new HashSet<Colours>(0);
     private Set<Friends> friendses = new HashSet<Friends>(0);
     private Set<InfluentialPersonalities> influentialPersonalitieses = new HashSet<InfluentialPersonalities>(0);
     private Set<Idols> idolses = new HashSet<Idols>(0);
     private Set<Schools> schoolses = new HashSet<Schools>(0);
     private Set<Allergies> allergieses = new HashSet<Allergies>(0);
     private Set<Hobbies> hobbieses = new HashSet<Hobbies>(0);
     private Set<Entertainment> entertainments = new HashSet<Entertainment>(0);
     private Set<Property> properties = new HashSet<Property>(0);
     private Set<Vehicles> vehicleses = new HashSet<Vehicles>(0);
     private Set<PrakrutiNidaan> prakrutiNidaans = new HashSet<PrakrutiNidaan>(0);
     private LifeStyle lifeStyle;
     private Set<FamilyRelations> familyRelationses = new HashSet<FamilyRelations>(0);

    public Pi() {
    }

	
    public Pi(String email) {
        this.email = email;
    }
    public Pi(String email, Long recid, String name, Short age, String gender, String religion, String maritalStatus, Short noOfChildren, Long mobile, String qualification, String profession, String company, String income, Set<Incidences> incidenceses, Address address, Set<Illness> illnesses, Menses menses, PhysicalParams physicalParams, Set<Tastes> tasteses, Travelling travelling, MealType mealType, SocialService socialService, Set<Addictions> addictionses, Exercise exercise, AcademicPerformance academicPerformance, Prayers prayers, Set<Colours> colourses, Set<Friends> friendses, Set<InfluentialPersonalities> influentialPersonalitieses, Set<Idols> idolses, Set<Schools> schoolses, Set<Allergies> allergieses, Set<Hobbies> hobbieses, Set<Entertainment> entertainments, Set<Property> properties, Set<Vehicles> vehicleses, Set<PrakrutiNidaan> prakrutiNidaans, LifeStyle lifeStyle, Set<FamilyRelations> familyRelationses) {
       this.email = email;
       this.recid = recid;
       this.name = name;
       this.age = age;
       this.gender = gender;
       this.religion = religion;
       this.maritalStatus = maritalStatus;
       this.noOfChildren = noOfChildren;
       this.mobile = mobile;
       this.qualification = qualification;
       this.profession = profession;
       this.company = company;
       this.income = income;
       this.incidenceses = incidenceses;
       this.address = address;
       this.illnesses = illnesses;
       this.menses = menses;
       this.physicalParams = physicalParams;
       this.tasteses = tasteses;
       this.travelling = travelling;
       this.mealType = mealType;
       this.socialService = socialService;
       this.addictionses = addictionses;
       this.exercise = exercise;
       this.academicPerformance = academicPerformance;
       this.prayers = prayers;
       this.colourses = colourses;
       this.friendses = friendses;
       this.influentialPersonalitieses = influentialPersonalitieses;
       this.idolses = idolses;
       this.schoolses = schoolses;
       this.allergieses = allergieses;
       this.hobbieses = hobbieses;
       this.entertainments = entertainments;
       this.properties = properties;
       this.vehicleses = vehicleses;
       this.prakrutiNidaans = prakrutiNidaans;
       this.lifeStyle = lifeStyle;
       this.familyRelationses = familyRelationses;
    }
   
     @Id 

    //@GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="email", unique=true, nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="recid")
    public Long getRecid() {
        return this.recid;
    }
    
    public void setRecid(Long recid) {
        this.recid = recid;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="age")
    public Short getAge() {
        return this.age;
    }
    
    public void setAge(Short age) {
        this.age = age;
    }

    
    @Column(name="gender")
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="religion")
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }

    
    @Column(name="marital_status")
    public String getMaritalStatus() {
        return this.maritalStatus;
    }
    
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    
    @Column(name="no_of_children")
    public Short getNoOfChildren() {
        return this.noOfChildren;
    }
    
    public void setNoOfChildren(Short noOfChildren) {
        this.noOfChildren = noOfChildren;
    }

    
    @Column(name="mobile")
    public Long getMobile() {
        return this.mobile;
    }
    
    public void setMobile(Long mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="qualification")
    public String getQualification() {
        return this.qualification;
    }
    
    public void setQualification(String qualification) {
        this.qualification = qualification;
    }

    
    @Column(name="profession")
    public String getProfession() {
        return this.profession;
    }
    
    public void setProfession(String profession) {
        this.profession = profession;
    }

    
    @Column(name="company")
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }

    
    @Column(name="income")
    public String getIncome() {
        return this.income;
    }
    
    public void setIncome(String income) {
        this.income = income;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pi")
    public Set<Incidences> getIncidenceses() {
        return this.incidenceses;
    }
    
    public void setIncidenceses(Set<Incidences> incidenceses) {
        this.incidenceses = incidenceses;
    }

@OneToOne(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pi")
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pi")
    public Set<Illness> getIllnesses() {
        return this.illnesses;
    }
    
    public void setIllnesses(Set<Illness> illnesses) {
        this.illnesses = illnesses;
    }

@OneToOne(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pi")
    public Menses getMenses() {
        return this.menses;
    }
    
    public void setMenses(Menses menses) {
        this.menses = menses;
    }

@OneToOne(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pi")
    public PhysicalParams getPhysicalParams() {
        return this.physicalParams;
    }
    
    public void setPhysicalParams(PhysicalParams physicalParams) {
        this.physicalParams = physicalParams;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pi")
    public Set<Tastes> getTasteses() {
        return this.tasteses;
    }
    
    public void setTasteses(Set<Tastes> tasteses) {
        this.tasteses = tasteses;
    }

@OneToOne(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pi")
    public Travelling getTravelling() {
        return this.travelling;
    }
    
    public void setTravelling(Travelling travelling) {
        this.travelling = travelling;
    }

@OneToOne(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pi")
    public MealType getMealType() {
        return this.mealType;
    }
    
    public void setMealType(MealType mealType) {
        this.mealType = mealType;
    }

@OneToOne(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pi")
    public SocialService getSocialService() {
        return this.socialService;
    }
    
    public void setSocialService(SocialService socialService) {
        this.socialService = socialService;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pi")
    public Set<Addictions> getAddictionses() {
        return this.addictionses;
    }
    
    public void setAddictionses(Set<Addictions> addictionses) {
        this.addictionses = addictionses;
    }

@OneToOne(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pi")
    public Exercise getExercise() {
        return this.exercise;
    }
    
    public void setExercise(Exercise exercise) {
        this.exercise = exercise;
    }

@OneToOne(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pi")
    public AcademicPerformance getAcademicPerformance() {
        return this.academicPerformance;
    }
    
    public void setAcademicPerformance(AcademicPerformance academicPerformance) {
        this.academicPerformance = academicPerformance;
    }

@OneToOne(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pi")
    public Prayers getPrayers() {
        return this.prayers;
    }
    
    public void setPrayers(Prayers prayers) {
        this.prayers = prayers;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pi")
    public Set<Colours> getColourses() {
        return this.colourses;
    }
    
    public void setColourses(Set<Colours> colourses) {
        this.colourses = colourses;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pi")
    public Set<Friends> getFriendses() {
        return this.friendses;
    }
    
    public void setFriendses(Set<Friends> friendses) {
        this.friendses = friendses;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pi")
    public Set<InfluentialPersonalities> getInfluentialPersonalitieses() {
        return this.influentialPersonalitieses;
    }
    
    public void setInfluentialPersonalitieses(Set<InfluentialPersonalities> influentialPersonalitieses) {
        this.influentialPersonalitieses = influentialPersonalitieses;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pi")
    public Set<Idols> getIdolses() {
        return this.idolses;
    }
    
    public void setIdolses(Set<Idols> idolses) {
        this.idolses = idolses;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pi")
    public Set<Schools> getSchoolses() {
        return this.schoolses;
    }
    
    public void setSchoolses(Set<Schools> schoolses) {
        this.schoolses = schoolses;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pi")
    public Set<Allergies> getAllergieses() {
        return this.allergieses;
    }
    
    public void setAllergieses(Set<Allergies> allergieses) {
        this.allergieses = allergieses;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pi")
    public Set<Hobbies> getHobbieses() {
        return this.hobbieses;
    }
    
    public void setHobbieses(Set<Hobbies> hobbieses) {
        this.hobbieses = hobbieses;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pi")
    public Set<Entertainment> getEntertainments() {
        return this.entertainments;
    }
    
    public void setEntertainments(Set<Entertainment> entertainments) {
        this.entertainments = entertainments;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pi")
    public Set<Property> getProperties() {
        return this.properties;
    }
    
    public void setProperties(Set<Property> properties) {
        this.properties = properties;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pi")
    public Set<Vehicles> getVehicleses() {
        return this.vehicleses;
    }
    
    public void setVehicleses(Set<Vehicles> vehicleses) {
        this.vehicleses = vehicleses;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pi")
    public Set<PrakrutiNidaan> getPrakrutiNidaans() {
        return this.prakrutiNidaans;
    }
    
    public void setPrakrutiNidaans(Set<PrakrutiNidaan> prakrutiNidaans) {
        this.prakrutiNidaans = prakrutiNidaans;
    }

@OneToOne(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pi")
    public LifeStyle getLifeStyle() {
        return this.lifeStyle;
    }
    
    public void setLifeStyle(LifeStyle lifeStyle) {
        this.lifeStyle = lifeStyle;
    }

@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="pi")
    public Set<FamilyRelations> getFamilyRelationses() {
        return this.familyRelationses;
    }
    
    public void setFamilyRelationses(Set<FamilyRelations> familyRelationses) {
        this.familyRelationses = familyRelationses;
    }
}


