package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Prayers generated by hbm2java
 */
@Entity
@Table(name="prayers", schema="test"
)
public class Prayers  implements java.io.Serializable {


     private String email;
     private Pi pi;
     private Short individualDaysPerWeek;
     private Short familyDaysPerWeek;
     private Short communityDaysPerWeek;

    public Prayers() {
    }

	
    public Prayers(Pi pi) {
        this.pi = pi;
    }
    public Prayers(Pi pi, Short individualDaysPerWeek, Short familyDaysPerWeek, Short communityDaysPerWeek) {
       this.pi = pi;
       this.individualDaysPerWeek = individualDaysPerWeek;
       this.familyDaysPerWeek = familyDaysPerWeek;
       this.communityDaysPerWeek = communityDaysPerWeek;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="pi"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="email", unique=true, nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Pi getPi() {
        return this.pi;
    }
    
    public void setPi(Pi pi) {
        this.pi = pi;
    }

    
    @Column(name="individual_days_per_week")
    public Short getIndividualDaysPerWeek() {
        return this.individualDaysPerWeek;
    }
    
    public void setIndividualDaysPerWeek(Short individualDaysPerWeek) {
        this.individualDaysPerWeek = individualDaysPerWeek;
    }

    
    @Column(name="family_days_per_week")
    public Short getFamilyDaysPerWeek() {
        return this.familyDaysPerWeek;
    }
    
    public void setFamilyDaysPerWeek(Short familyDaysPerWeek) {
        this.familyDaysPerWeek = familyDaysPerWeek;
    }

    
    @Column(name="community_days_per_week")
    public Short getCommunityDaysPerWeek() {
        return this.communityDaysPerWeek;
    }
    
    public void setCommunityDaysPerWeek(Short communityDaysPerWeek) {
        this.communityDaysPerWeek = communityDaysPerWeek;
    }




}


