package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PropertyId generated by hbm2java
 */
@Embeddable
public class PropertyId  implements java.io.Serializable {


     private String email;
     private String propertyType;

    public PropertyId() {
    }

    public PropertyId(String email, String propertyType) {
       this.email = email;
       this.propertyType = propertyType;
    }
   


    @Column(name="email", nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }


    @Column(name="property_type", nullable=false)
    public String getPropertyType() {
        return this.propertyType;
    }
    
    public void setPropertyType(String propertyType) {
        this.propertyType = propertyType;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PropertyId) ) return false;
		 PropertyId castOther = ( PropertyId ) other; 
         
		 return ( (this.getEmail()==castOther.getEmail()) || ( this.getEmail()!=null && castOther.getEmail()!=null && this.getEmail().equals(castOther.getEmail()) ) )
 && ( (this.getPropertyType()==castOther.getPropertyType()) || ( this.getPropertyType()!=null && castOther.getPropertyType()!=null && this.getPropertyType().equals(castOther.getPropertyType()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEmail() == null ? 0 : this.getEmail().hashCode() );
         result = 37 * result + ( getPropertyType() == null ? 0 : this.getPropertyType().hashCode() );
         return result;
   }   


}


