package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Schools generated by hbm2java
 */
@Entity
@Table(name="schools"
)
public class Schools  implements java.io.Serializable {


     private SchoolsId id;
     private Pi pi;
     private String medium;
     private String faculty;
     private String board;
     private String subjects;

    public Schools() {
    }

	
    public Schools(SchoolsId id, Pi pi) {
        this.id = id;
        this.pi = pi;
    }
    public Schools(SchoolsId id, Pi pi, String medium, String faculty, String board, String subjects) {
       this.id = id;
       this.pi = pi;
       this.medium = medium;
       this.faculty = faculty;
       this.board = board;
       this.subjects = subjects;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="email", column=@Column(name="email", nullable=false) ), 
        @AttributeOverride(name="schoolName", column=@Column(name="school_name", nullable=false) ), 
        @AttributeOverride(name="class_", column=@Column(name="class", nullable=false) ) } )
    public SchoolsId getId() {
        return this.id;
    }
    
    public void setId(SchoolsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="email", nullable=false, insertable=false, updatable=false)
    public Pi getPi() {
        return this.pi;
    }
    
    public void setPi(Pi pi) {
        this.pi = pi;
    }

    
    @Column(name="medium")
    public String getMedium() {
        return this.medium;
    }
    
    public void setMedium(String medium) {
        this.medium = medium;
    }

    
    @Column(name="faculty")
    public String getFaculty() {
        return this.faculty;
    }
    
    public void setFaculty(String faculty) {
        this.faculty = faculty;
    }

    
    @Column(name="board")
    public String getBoard() {
        return this.board;
    }
    
    public void setBoard(String board) {
        this.board = board;
    }

    
    @Column(name="subjects")
    public String getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(String subjects) {
        this.subjects = subjects;
    }




}


