package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SchoolsId generated by hbm2java
 */
@Embeddable
public class SchoolsId  implements java.io.Serializable {


     private String email;
     private String schoolName;
     private String class_;

    public SchoolsId() {
    }

    public SchoolsId(String email, String schoolName, String class_) {
       this.email = email;
       this.schoolName = schoolName;
       this.class_ = class_;
    }
   


    @Column(name="email", nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }


    @Column(name="school_name", nullable=false)
    public String getSchoolName() {
        return this.schoolName;
    }
    
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }


    @Column(name="class", nullable=false)
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SchoolsId) ) return false;
		 SchoolsId castOther = ( SchoolsId ) other; 
         
		 return ( (this.getEmail()==castOther.getEmail()) || ( this.getEmail()!=null && castOther.getEmail()!=null && this.getEmail().equals(castOther.getEmail()) ) )
 && ( (this.getSchoolName()==castOther.getSchoolName()) || ( this.getSchoolName()!=null && castOther.getSchoolName()!=null && this.getSchoolName().equals(castOther.getSchoolName()) ) )
 && ( (this.getClass_()==castOther.getClass_()) || ( this.getClass_()!=null && castOther.getClass_()!=null && this.getClass_().equals(castOther.getClass_()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEmail() == null ? 0 : this.getEmail().hashCode() );
         result = 37 * result + ( getSchoolName() == null ? 0 : this.getSchoolName().hashCode() );
         result = 37 * result + ( getClass_() == null ? 0 : this.getClass_().hashCode() );
         return result;
   }   


}


