package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * SocialService generated by hbm2java
 */
@Entity
@Table(name="social_service", schema="test"
)
public class SocialService  implements java.io.Serializable {


     private String email;
     private Pi pi;
     private Short cashTimesPerWeek;
     private Short cashAmount;
     private Short kindTimesPerWeek;
     private Short kindAmount;
     private Short socialServiceHoursPerWeek;
     private String areaOfWork;

    public SocialService() {
    }

	
    public SocialService(Pi pi) {
        this.pi = pi;
    }
    public SocialService(Pi pi, Short cashTimesPerWeek, Short cashAmount, Short kindTimesPerWeek, Short kindAmount, Short socialServiceHoursPerWeek, String areaOfWork) {
       this.pi = pi;
       this.cashTimesPerWeek = cashTimesPerWeek;
       this.cashAmount = cashAmount;
       this.kindTimesPerWeek = kindTimesPerWeek;
       this.kindAmount = kindAmount;
       this.socialServiceHoursPerWeek = socialServiceHoursPerWeek;
       this.areaOfWork = areaOfWork;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="pi"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="email", unique=true, nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Pi getPi() {
        return this.pi;
    }
    
    public void setPi(Pi pi) {
        this.pi = pi;
    }

    
    @Column(name="cash_times_per_week")
    public Short getCashTimesPerWeek() {
        return this.cashTimesPerWeek;
    }
    
    public void setCashTimesPerWeek(Short cashTimesPerWeek) {
        this.cashTimesPerWeek = cashTimesPerWeek;
    }

    
    @Column(name="cash_amount")
    public Short getCashAmount() {
        return this.cashAmount;
    }
    
    public void setCashAmount(Short cashAmount) {
        this.cashAmount = cashAmount;
    }

    
    @Column(name="kind_times_per_week")
    public Short getKindTimesPerWeek() {
        return this.kindTimesPerWeek;
    }
    
    public void setKindTimesPerWeek(Short kindTimesPerWeek) {
        this.kindTimesPerWeek = kindTimesPerWeek;
    }

    
    @Column(name="kind_amount")
    public Short getKindAmount() {
        return this.kindAmount;
    }
    
    public void setKindAmount(Short kindAmount) {
        this.kindAmount = kindAmount;
    }

    
    @Column(name="social_service_hours_per_week")
    public Short getSocialServiceHoursPerWeek() {
        return this.socialServiceHoursPerWeek;
    }
    
    public void setSocialServiceHoursPerWeek(Short socialServiceHoursPerWeek) {
        this.socialServiceHoursPerWeek = socialServiceHoursPerWeek;
    }

    
    @Column(name="area_of_work")
    public String getAreaOfWork() {
        return this.areaOfWork;
    }
    
    public void setAreaOfWork(String areaOfWork) {
        this.areaOfWork = areaOfWork;
    }




}


