package com.srti.gbb.entity;
// Generated Apr 15, 2014 4:24:33 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Travelling generated by hbm2java
 */
@Entity
@Table(name="travelling"
)
public class Travelling  implements java.io.Serializable {


     private String email;
     private Pi pi;
     private Short indState;
     private Short indNational;
     private Short indInternational;
     private Short familyState;
     private Short familyNational;
     private Short familyInternational;
     private Short friendsState;
     private Short friendsNational;
     private Short friendsInternational;

    public Travelling() {
    }

	
    public Travelling(Pi pi) {
        this.pi = pi;
    }
    public Travelling(Pi pi, Short indState, Short indNational, Short indInternational, Short familyState, Short familyNational, Short familyInternational, Short friendsState, Short friendsNational, Short friendsInternational) {
       this.pi = pi;
       this.indState = indState;
       this.indNational = indNational;
       this.indInternational = indInternational;
       this.familyState = familyState;
       this.familyNational = familyNational;
       this.familyInternational = familyInternational;
       this.friendsState = friendsState;
       this.friendsNational = friendsNational;
       this.friendsInternational = friendsInternational;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="pi"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="email", unique=true, nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Pi getPi() {
        return this.pi;
    }
    
    public void setPi(Pi pi) {
        this.pi = pi;
    }

    
    @Column(name="ind_state")
    public Short getIndState() {
        return this.indState;
    }
    
    public void setIndState(Short indState) {
        this.indState = indState;
    }

    
    @Column(name="ind_national")
    public Short getIndNational() {
        return this.indNational;
    }
    
    public void setIndNational(Short indNational) {
        this.indNational = indNational;
    }

    
    @Column(name="ind_international")
    public Short getIndInternational() {
        return this.indInternational;
    }
    
    public void setIndInternational(Short indInternational) {
        this.indInternational = indInternational;
    }

    
    @Column(name="family_state")
    public Short getFamilyState() {
        return this.familyState;
    }
    
    public void setFamilyState(Short familyState) {
        this.familyState = familyState;
    }

    
    @Column(name="family_national")
    public Short getFamilyNational() {
        return this.familyNational;
    }
    
    public void setFamilyNational(Short familyNational) {
        this.familyNational = familyNational;
    }

    
    @Column(name="family_international")
    public Short getFamilyInternational() {
        return this.familyInternational;
    }
    
    public void setFamilyInternational(Short familyInternational) {
        this.familyInternational = familyInternational;
    }

    
    @Column(name="friends_state")
    public Short getFriendsState() {
        return this.friendsState;
    }
    
    public void setFriendsState(Short friendsState) {
        this.friendsState = friendsState;
    }

    
    @Column(name="friends_national")
    public Short getFriendsNational() {
        return this.friendsNational;
    }
    
    public void setFriendsNational(Short friendsNational) {
        this.friendsNational = friendsNational;
    }

    
    @Column(name="friends_international")
    public Short getFriendsInternational() {
        return this.friendsInternational;
    }
    
    public void setFriendsInternational(Short friendsInternational) {
        this.friendsInternational = friendsInternational;
    }




}


